name: Agentic Continuous Integration

on:
  push:
    branches: [agentic-development]
  pull_request:
    branches: [agentic-development]
  schedule:
    - cron: "0 0,8,16 * * *"
  workflow_dispatch:

jobs:
  build-test:
    name: Run CI tasks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: agentic-development

      - name: Setup PowerShell
        run: |
          if ! command -v pwsh &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y wget apt-transport-https software-properties-common
            wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get update
            sudo apt-get install -y powershell
          fi

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Lint PowerShell scripts
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path .
          $results | ForEach-Object {
            Write-Host "::warning file=$($_.ScriptName),line=$($_.Line)::$($_.Message)"
          }

      - name: Run Pester tests if present
        shell: pwsh
        run: |
          if (Get-Command Invoke-Pester -ErrorAction SilentlyContinue) {
            Invoke-Pester -Output Detailed
          } else {
            Write-Host "Pester not installed; skipping tests."
          }

      - name: Run forensic script (sanity check)
        shell: pwsh
        run: |
          ./android-forensic-suite.ps1 -OutputPath "agentic-output" -SkipLogCollection
